server:
  port: 8888
spring:
  application:
    name: cloud-config
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/pnkjsmwl/account.git
          clone-on-start: true